name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - project/**
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    # Debug secrets
    - name: Debug Kaggle Secret
      run: echo "${{ secrets.KAGGLE_CONFIG_DIR }}" | head -n 1

    # Install Kaggle CLI and Dependencies
    - name: Install Kaggle CLI and Dependencies
      run: |
        mkdir -p ~/.kaggle
        echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
        pip install -r requirements.txt

    # Make pipeline.sh and tests.sh executable
    - name: Make Scripts Executable
      run: |
        chmod +x project/pipeline.sh
        chmod +x project/tests.sh

    # Debug data folder before pipeline
    - name: Debug Data Folder
      run: ls -R ./data || echo "Data folder is empty or missing"

    # Clear old data before running pipeline
    - name: Clear Old Data
      run: rm -rf ./data || echo "No data folder to clear"

    # Run pipeline.sh
    - name: Run Pipeline Script
      run: bash project/pipeline.sh

    # Debug data folder after pipeline
    - name: Debug Data Folder After Pipeline
      run: ls -R ./data || echo "Data folder is empty after pipeline"

    # Run tests.sh
    - name: Run Tests
      run: bash project/tests.sh

    # Save logs for debugging
    - name: Save Logs for Debugging
      if: failure()
      run: |
        echo "Pipeline Script Logs:"
        cat project/pipeline.sh
        echo "Test Script Logs:"
        cat project/tests.sh
        echo "Contents of Data Folder:"
        ls -R ./data || echo "Data folder missing"
