name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - project/**
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      use_mock_data:
        description: "Use mock data (true/false)"
        required: true
        default: "true"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    # Install Dependencies
    - name: Install Dependencies
      run: pip install -r requirements.txt

    # Install Kaggle CLI and Configure Credentials (for real data)
    - name: Configure Kaggle CLI
      if: ${{ inputs.use_mock_data == 'false' }}
      run: |
        mkdir -p ~/.kaggle
        echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    # Make pipeline.sh and tests.sh executable
    - name: Make Scripts Executable
      run: |
        chmod +x project/pipeline.sh
        chmod +x project/tests.sh

    # Clear old data before running pipeline
    - name: Clear Old Data
      run: rm -rf ./data || echo "No data folder to clear"

    # Run tests based on input
    - name: Run Tests
      env:
        USE_MOCK_DATA: ${{ inputs.use_mock_data }}
      run: bash project/tests.sh

    # Save logs for debugging
    - name: Save Logs for Debugging
      if: failure()
      run: |
        echo "Pipeline Script Logs:"
        cat project/pipeline.sh
        echo "Test Script Logs:"
        cat project/tests.sh
        echo "Contents of Data Folder:"
        ls -R ./data || echo "Data folder missing"
